config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products do
  	resources :comments , only: [:create, :update, :destroy]
  end
  
  resources :order_items
  resources :charges, only: [:new, :create]
  resource :cart, only: [:show]

  get '/charges/validate_coupon', to: 'charges#validate_coupon', as: :validate_coupon
  get 'index' => 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'contact' => 'pages#contact', as: 'contact'
    
  root to: "products#index"
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@order_items = current_order.order_items
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:8%">Quantity</th>
        <th style="width:22%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
      </tr>
    </thead>
    <% @total %>
    <% if @order_items.size > 0 %>
      <% @order_items.each do |item| %>
        <% @total = item  %>
        <tbody>
          <tr>
            <td data-th="Product">
              <div class="row">
                <div class="col-sm-2 hidden-xs">
                  <%= image_tag url_for(item.product.images.first), class: "img-responsive"%>
                </div>
                <div class="col-sm-10">
                  <h4 class="nomargin"> <%=item.product.name%></h4>
                  <p><%=item.product.description%></p>
                </div>
              </div>
            </td>
            <%= form_for(item, remote: true) do |f| %>
              <td data-th="Price">$ <%= item.product.price %></td>
              <td data-th="Quantity">
                <%= f.number_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control text-center update-item-quantity',data: { item_id: item.id },
                      id: "item-quantity-#{item.id}"%>
              </td>
              <td data-th="Subtotal" id="update-unit-total-<%=item.id%>" class="text-center">$<%= item.total_price %></td>
              <span hidden ></span>
              <td class="actions" data-th="">
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, item, method: :delete, remote: true, class: 'btn btn-danger btn-sm '%>
              </td>
            <% end %>
          </tr>
          </tbody>
          <% end %>
          <tfoot>
            <tr class="visible-xs">
              </td>
            </tr>
              <tr>
                <td><%= link_to '<i class="fa fa-angle-left"></i> Continue Shopping'.html_safe, products_path, class: "btn btn-warning" %></td>
                <td colspan="2" class="hidden-xs"></td>
                <td id="order-subtotal" class="hidden-xs text-center"><strong>Total: $<%= @total.order.subtotal%></strong></td>

                <td><%= link_to 'Checkout <i class="fa fa-angle-right"></i>'.html_safe, new_charge_path, class: 'btn btn-success btn-block'%></td>
              </tr>
            <% else %>
            <tr>
              <td style="text-align: center;"><h4 class="stock">Cart is Empty!!</h4></td>
            </tr>
          </tfoot>
      </table>
    <% end %>
</div>