config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products do
  	resources :comments , only: [:create, :update, :destroy]
  end
  
  resources :order_items
  resources :charges, only: [:new, :create]
  resource :cart, only: [:show]

  get '/charges/validate_coupon', to: 'charges#validate_coupon', as: :validate_coupon
  get 'index' => 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'contact' => 'pages#contact', as: 'contact'
    
  root to: "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy 
	has_many :order_items
	has_many_attached :images
	validates :name, presence: true
	validates :price, presence: true
	validates :quantity, presence: true 
	validates :description, presence: true 
	validate :image_type

	after_save ThinkingSphinx::RealTime.callback_for(:product)

	def image_type
		images.each do |image|
			if !image.content_type.in?(%('image/jpeg image/png'))
				errors.add(:images, 'Image needs to be JPEG or PNG')
			end
		end 
	end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.search(params[:search])
    @results_not_found = @products.empty?
    @products = Product.all if @products.empty?
    if user_signed_in?
      @order_item = current_order.order_items.new
    end
  end

  def show
    if user_signed_in?
      @order_item = current_order.order_items.new
    end  
  end

  def new
    @product = current_user.products.new    
  end

  def edit
  end

  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <div>
    <div id = "div1" class="container">
      <%= form_with(model: product, local: true) do |form| %>
        <% if product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
            <% product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
      <div class="jumbotron">
        <form>
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, autofocus: true, class: "form-control",
            placeholder: "Product Name", required: true  %>
          </div>

          <div class="field">
            <%= form.label :price %>
            <%= form.number_field :price, class: "form-control", placeholder: "Product Price", required: true  %>
          </div>

          <div class="field">
            <%= form.label :quantity %>
            <%= form.number_field :quantity, class: "form-control", placeholder: "Product Quantity", required: true  %>
          </div>

          <div class="form-group">
            <label class="btn btn-info btn-product-image"><i class="fa fa-upload" aria-hidden="true"></i>  Images
                <% if product.images.empty? %>
                  <%= form.file_field :images, required: true, multiple: true %>
                <% else %>
                  <%= form.file_field :images, multiple: true %>
                <% end %>
            </label>
            <small  class = "form-text text-muted" >This product has <%= product.images.count %> pictures uploaded.</small>
          </div>
          

      
          <div class="form-group shadow-textarea">
            <label for="exampleFormControlTextarea6">Product Description</label>
            <%= form.text_area :description, class: "form-control z-depth-1", id: "exampleFormControlTextarea6", rows: "3", placeholder: "Write something here...", required: true  %>
          </div>


          <div class="actions">
            <%= form.submit "Save", class: "btnButton" %>
          </div>

         </form>
      </div>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<div class="container">
	<h1>Editing Product</h1>
</div>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="container">
  <% if @results_not_found %>
    <h4 class="reviews"><i class="fa fa-search"></i> Sorry, your search did not match any products. Please try again.</h4>
  <% end %>
  <h3 class="h3">Products </h3>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6">
        <div class="product-grid2">
          <div class="product-image2">
            <a href="#">
              <%= image_tag url_for(product.images.first), class: "pic-1"%>
              <% if product.images.count > 1 %>
                <%= image_tag url_for(product.images.second), class: "pic-2"%>
              <% else %>
                <%= image_tag('default_product.png', class: "pic-2") %>
              <% end %>
            </a>

              <ul class="social">
                <li>
                  <%= link_to '<i class="fa fa-eye"></i>'.html_safe, product %></li>
                <li>
                <% if user_signed_in? %>
                  <%= form_for (@order_item) do |f|   %>
                    <%= f.hidden_field :product_id, value: product.id %>
                    <%= f.hidden_field :quantity, value: 1 %>
                      <% if product.user != current_user && product.quantity > 0 %>
                        <li><%= f.button class: 'btn btn-light btn-circle btn-sm' do %>
                          <i class="fa fa-shopping-cart fa-lg"></i>
                        </li>
                      <% end %>
              </ul>
                <% if product.quantity > 0 %>
                  <%= f.submit "Add to cart", class: 'add-to-cart' %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          </div>
            <div class="product-content">
              <h3><%=product.name%></h3>
              <span class="price">$ <%= product.price %></span>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<hr>

app/views/products/new.html.erb
<div class="container">
	<h1>New Product</h1>
</div>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="card">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1">
              <%= image_tag(@product.images.first) %>
            </div>
          </div>
          <ul class="preview-thumbnail nav nav-tabs">
            <%- @product.images.each do |image| %>
              <li class="active">
                <a data-target="#pic-1" data-toggle="tab">
                  <%= image_tag(image) %>
                </a>
              </li>
            <%- end %>
          </ul>
                  
        </div>
        <div class="details col-md-6">
            <h3 class="product-title"><%= @product.name %></h3>

            <p class="product-description"> <%= @product.description %> </p>

            <h4 class="price">Current Price:  <span><span id="dollar">$</span>  <%= @product.price %></span></h4>
            <% if @product.quantity > 0 %>
              <h4>Quantity: <%= @product.quantity %> </h4>
            <% else %>
              <h4 class="stock">Out of Stock</h4>
            <% end %>

            <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
            
            
            <div class="action">
              <% if @product.user == current_user %>
                <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-info" %>
                <%= link_to 'Destroy', @product,class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
              <% else %> 
                <% if user_signed_in? && @product.quantity > 0 %>
                  <%= form_for (@order_item) do |f| %>
                    <%= f.hidden_field :product_id, value: @product.id %>
                    <%= f.hidden_field :quantity, value: 1 %>
                    <%= f.submit "Add to cart", class: 'add-to-cart btn btn-default' %>
                <% end %>
              <% end %>

              <% end %>
                
            </div>
        </div>
      </div>
           
    </div>
  </div>
  <% if  @product.comments != nil? %>
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1" id="logout">
          <h3 class="reviews">User Reviews</h3>
          <div class="tab-content">
            <ul role="tablist">
              <div id ="comments-logout">
                <%= render partial: 'comments/comment', collection: @product.comments, as: :comment %>
              </div>
            </ul>  
            <% if user_signed_in? %>
            <% unless @product.user == current_user  %>
              <%= render 'comments/form' %>
            <% end %>
          <% end %>          
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>