config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products do
  	resources :comments , only: [:create, :update, :destroy]
  end
  
  resources :order_items
  resources :charges, only: [:new, :create]
  resource :cart, only: [:show]

  get '/charges/validate_coupon', to: 'charges#validate_coupon', as: :validate_coupon
  get 'index' => 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'contact' => 'pages#contact', as: 'contact'
    
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
	belongs_to :coupon
 	validates_presence_of :amount, :stripe_id
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/coupon.rb
class Coupon < ApplicationRecord
	has_many :charges
  validates_presence_of :code, :discount_percent
  validates_uniqueness_of :code

  def self.get(code)
    where(code: normalize_code(code)).
    where('expires_at > ? OR expires_at IS NULL', Time.now).
    take
  end

  def apply_discount(amount)
    discount = amount * (self.discount_percent * 0.01)
    (amount - discount.to_i)
  end

  def discount_percent_human
    if discount_percent.present?
      discount_percent.to_s + "%"
    end
  end

  private

  def self.normalize_code(code)
    code.gsub(/\s+/, '').upcase
  end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :user

	before_save :set_subtotal
	before_destroy :update_product_quantity

	def subtotal
		order_items.collect {|order_item| order_item.valid? ?  (order_item.unit_price*order_item.quantity) : 0}.sum
	end


	private
		def set_subtotal
			# self[:subtotal] = subtotal
			self.subtotal = subtotal
		end

		def update_product_quantity
			order_items.each do |item|
				item.product.quantity -= item.quantity
				item.product.save
			end
		end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

	before_save :set_unit_price
	before_save :set_total_price
	before_update :set_total_price
	validate :product_quantity, on: :update


	def unit_price
		if persisted?
			self[:unit_price]
		else
			product.price 
		end
	end

	def total_price
		unit_price*quantity
	end

	private

		def set_unit_price
			self[:unit_price] = unit_price 
		end

		def set_total_price
			self[:total_price] = quantity * set_unit_price
		end

		def product_quantity
			if quantity > product.quantity
				update(quantity: quantity_was, total_price: total_price_was)
				errors.add(:base, 'Selected Quantity must be less than available quantity')
			end
		end


end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy 
	has_many :order_items
	has_many_attached :images
	validates :name, presence: true
	validates :price, presence: true
	validates :quantity, presence: true 
	validates :description, presence: true 
	validate :image_type

	after_save ThinkingSphinx::RealTime.callback_for(:product)

	def image_type
		images.each do |image|
			if !image.content_type.in?(%('image/jpeg image/png'))
				errors.add(:images, 'Image needs to be JPEG or PNG')
			end
		end 
	end 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :comments, dependent: :destroy 
  has_many :orders
  has_one_attached :avatar

  validate :image_type

  def image_type
    if avatar.attached?
  		if !avatar.content_type.in?(%('image/jpeg image/png'))
        errors.add(:images, 'Image needs to be JPEG or PNG')
      end
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@order_items = current_order.order_items
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@total = current_order.subtotal
	end
	
	def validate_coupon
		@amount = params[:total].to_i
	  @final_amount = @amount

	  @code = params[:couponCode]

	  if !@code.blank?
		  @coupon = Coupon.get(@code)
		    if @coupon.nil?
		    	message = "invalid"

		    	respond_to do |format|
						format.json { render json: { message: message} }
					end
					
		    else
		      @final_amount = @coupon.apply_discount(@amount.to_i)
	    	  @discount_amount = (@amount - @final_amount)
	    	  message = "applied"
	    	  respond_to do |format|
						format.json { render json: { message: message, final_amount: @final_amount, discount: @coupon.discount_percent_human } }
					end
		    end
		end
	end

	def create
	  @amount = params[:discounted_total].to_i * 100
	  @coupon = Coupon.get(params[:couponCode])
	  @final_amount = @coupon&.apply_discount(@amount) || @amount
	  @discount_amount = (@amount - @final_amount)

	
	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount.to_i,
	    description: 'Rails Stripe customer',
	    currency: 'usd',
	  })

	  current_order.destroy
	  session[:order_id] = nil

		rescue Stripe::CardError => e
  		flash[:error] = e.message
  		redirect_to new_charge_path
  	end
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
	  @comment = @product.comments.new(comment_params)
	  @comment.user = current_user

	  if @comment.save
	    respond_to do |format|
	    	format.js
	    end
	  end
 	end

 	def destroy
	  @product = Product.find(params[:product_id])
	  @comment = @product.comments.find(params[:id])
	  
	  if @comment.destroy
	    respond_to do |format|
	    	format.js
	    end
	  end
	end

private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_order
		if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			if user_signed_in?
				order = Order.create(user_id: current_user.id)
				session[:order_id] = order.id
				order
			end
		end
	end

	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
	end
	
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
    

            <%= link_to image_tag("logo.png", class: "navbar-brand brand_img") , products_path %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "About Us", about_path, class: "active about-us" %></li>
              <li><%= link_to "Contact Us", contact_path,class: "active" %></li>
            </ul>
            <% if controller_name == 'products' && action_name == 'index' %>
            <form class="navbar-form navbar-left">
                <%= form_for products_path, :method => 'get' do %>
                  <div class="input-group">
                    <%= text_field_tag :search, params[:search], class:"form-control" %> 
                  <div class="input-group-btn">
                    <%= submit_tag "Search", :name => nil, class:"btn btn-warning"%>
                  </div>
                <% end -%>
              </div>
            </form> 
            <% end %>
            </li>

            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li ><%= link_to 'Add Product' , new_product_path %></li>
              <li class="cart"><%= link_to image_tag("cart.png", class: "cart_nav_icon") ,cart_path %></li>
              <li class="dropdown">
                <a id="nav_drop" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name%>
                  <% if current_user.avatar.attached? %>
                    <%= image_tag(current_user.avatar , class: "img-circular" , id:"nav_image") %>
                  <% else %>
                    <%= image_tag('default.png' , class: "img-circular" , id:"nav_image") %>
                  <% end %>
                  <span class="caret"></span>
                </a>
                
                <ul class="dropdown-menu">
                  <li><%= link_to 'Account' , edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Sign Out' , destroy_user_session_path, :method => :delete%></li>
                </ul>
              </li>
            <% else %>
                <li><%= link_to 'Sign In' , new_user_session_path %></li>
                <li><%= link_to 'Sign Up' , new_user_registration_path %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="row">
        <!-- Team member -->
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                <div class="mainflip">
                    <div class="frontside">
                        <div class="card">
                            <div class="card-body text-center">
                                <%= image_tag ("sadique.png") %>
                                <h4 class="card-title">SADIQUE</h4>
                                <p class="card-text">Sadique has done all the development phase including front-end and back-end</p>
                                <a href="#" class="btn btn-warning btn-sm plus"><i class="fa fa-plus plus"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="backside">
                        <div class="card">
                            <div class="card-body text-center mt-4">
                                <h4 class="card-title">Sadique Anwar</h4>
                                <p class="card-text">This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.</p>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-skype"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-google"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                <div class="mainflip">
                    <div class="frontside">
                        <div class="card">
                            <div class="card-body text-center">
                                <%= image_tag ("fazal.png") %>
                                <h4 class="card-title">FAZAL</h4>
                                <p class="card-text">Mentor and work buddy who helped me and guided me throughtout the project.</p>
                                <a href="#" class="btn btn-warning btn-sm plus"><i class="fa fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="backside">
                        <div class="card">
                            <div class="card-body text-center mt-4">
                                <h4 class="card-title">Fazal Karim</h4>
                                <p class="card-text">This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.</p>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-skype"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-google"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                <div class="mainflip">
                    <div class="frontside">
                        <div class="card">
                            <div class="card-body text-center">
                                <%= image_tag ("ahsan.png") %>
                                <h4 class="card-title">AHSAN</h4>
                                <p class="card-text">Project Manager, who helped in planning, executing, and closing the work of a team to achieve specific goals</p>
                                <a href="#" class="btn btn-warning btn-sm plus"><i class="fa fa-plus"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="backside">
                        <div class="card">
                            <div class="card-body text-center mt-4">
                                <h4 class="card-title">Ahsan Illahi</h4>
                                <p class="card-text">This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.This is basic card with image on top, title, description and button.</p>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-skype"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a class="social-icon text-xs-center" target="_blank" href="#">
                                            <i class="fa fa-google"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/contact.html.erb
<body class="contact_body">
    <div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="post">
                <h3>Drop Us a Message</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>
</body>